[package]
name = "kvs"
version = "0.1.0"
authors = ["Kafji <k@kafji.net>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.1"
dotenv_codegen = "0.15.0"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
tempfile = "3.0.7"
walkdir = "2.2.7"
