[package]
name = "exercises"
version = "0.0.1"
authors = ["Kafji <k@kafji.net>"]
edition = "2018"

[dependencies]
backtrace = "0.3"
serde = { version = "1.0", features = ["derive"] }
slog = "2.5"
slog-async = "2.5"
slog-term = "2.6"
smallvec = "1.4"
